name: Test

on: 
  push:
  pull_request:

jobs:
  mocha:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    services:
      postgres:
        image: postgres:15
        ports:
          - 54312:5432
        env:
          POSTGRES_DB: test-misskey
          POSTGRES_HOST_AUTH_METHOD: trust
      redis:
        image: redis:6
        ports:
          - 56312:6379

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: corepack enable
    - name: Install dependencies
      run: pnpm i
    - name: Copy Configure
      run: cp .github/misskey/test.yml .config
    - name: Build
      run: pnpm build
    - name: Test
      run: pnpm mocha